//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment01
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearningEvent()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int Id { get; set; }
        public string eventType { get; set; }
        public System.DateTime eventDateTime { get; set; }
        public int eventDuration { get; set; }
        public int moduleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Module Module { get; set; }
    }
}
