//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id { get; set; }
        public System.DateTime regDate { get; set; }
        public int studentID { get; set; }
        public int moduleID { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Student Student { get; set; }
    }
}
